export const data_all = [
  {
    name: "Stewed Mushrooms",
    image: require("../../assets/namkho.jpg"),
    rating: 3,
    price: "$12",
    type: "Dessert",
    id: "1",
  },
  {
    name: "Jackfruit Fried",
    image: require("../../assets/mitkho.jpg"),
    rating: 5,
    price: "$15",
    type: "Dessert",
    id: "2",
  },
  {
    name: "Noodles",
    image: require("../../assets/hutieu.jpg"),
    rating: 4,
    type: "Main course",
    price: "$20",
    id: "3",
  },
  {
    name: "Beef",
    image: require("../../assets/cuonlalot.jpg"),
    rating: 2,
    price: "$12",
    type: "Main course",
    id: "4",
  },
  {
    name: "Salad dressing",
    image: require("../../assets/cuondiep.jpg"),
    rating: 5,
    type: "Other",
    price: "$13",
    id: "5",
  },
  {
    name: "Jackfruit warehouse",
    image: require("../../assets/mitkho.jpg"),
    price: "$15",
    rating: 5,
    type: "Other",
    id: "6",
  },
];
